const test2 = [
  {
    name: "T8_POTION_COOLDOWN",
    ruName: "Эликсир яда",
    index: "550",
    slot: "potion",
  },
  {
    name: "T8_POTION_CLEANSE",
    ruName: "Эликсир невидимости",
    index: "554",
    slot: "potion",
  },
  {
    name: "T6_POTION_HEAL",
    ruName: "Эликсир здоровья",
    index: "490",
    slot: "potion",
  },
  {
    name: "T6_POTION_ENERGY",
    ruName: "Эликсир энергии",
    index: "502",
    slot: "potion",
  },
  {
    name: "T7_POTION_REVIVE",
    ruName: "Зелье гиганта",
    index: "514",
    slot: "potion",
  },
  {
    name: "T7_POTION_STONESKIN",
    ruName: "Эликсир защиты",
    index: "526",
    slot: "potion",
  },
  {
    name: "T7_POTION_SLOWFIELD",
    ruName: "Вязкая настойка",
    index: "538",
    slot: "potion",
  },
  {
    name: "T7_POTION_MOB_RESET",
    ruName: "Успокаивающее зелье",
    index: "566",
    slot: "potion",
  },
  {
    name: "T7_POTION_CLEANSE2",
    ruName: "Очищающее зелье",
    index: "578",
    slot: "potion",
  },
  {
    name: "T7_POTION_ACID",
    ruName: "Кислотное зелье",
    index: "590",
    slot: "potion",
  },
  {
    name: "T8_POTION_BERSERK",
    ruName: "Зелье берсерка",
    index: "602",
    slot: "potion",
  },
  {
    name: "T8_POTION_LAVA",
    ruName: "Зелье адского пламени",
    index: "614",
    slot: "potion",
  },
  {
    name: "T8_POTION_GATHER",
    ruName: "Зелье собирателя",
    index: "626",
    slot: "potion",
  },
  {
    name: "T8_POTION_TORNADO",
    ruName: "Буря в стакане",
    index: "638",
    slot: "potion",
  },
  {
    name: "T8_OFF_SHIELD",
    ruName: "Щит",
    index: "1885",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_TOWERSHIELD_UNDEAD",
    ruName: "Саркофаг",
    index: "1910",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_SHIELD_HELL",
    ruName: "Щит негодяя",
    index: "1935",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_SPIKEDSHIELD_MORGANA",
    ruName: "Лицелом",
    index: "1960",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_SHIELD_AVALON",
    ruName: "Эгида звезд",
    index: "1985",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_BOOK",
    ruName: "Книга заклинаний",
    index: "2012",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_ORB_MORGANA",
    ruName: "Око тайны",
    index: "2037",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_DEMONSKULL_HELL",
    ruName: "Череп-трофей",
    index: "2062",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_TOTEM_KEEPER",
    ruName: "Корень природы",
    index: "2087",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_CENSER_AVALON",
    ruName: "Небесное кадило",
    index: "2112",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_TORCH",
    ruName: "Факел",
    index: "2138",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_HORN_KEEPER",
    ruName: "Туманный зов",
    index: "2163",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_TALISMAN_AVALON",
    ruName: "Священный скипетр",
    index: "2188",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_LAMP_UNDEAD",
    ruName: "Могильная свеча",
    index: "2213",
    slot: "off_hand",
  },
  {
    name: "T8_OFF_JESTERCANE_HELL",
    ruName: "Зловещая трость",
    index: "2238",
    slot: "off_hand",
  },
  { name: "T8_CAPE", ruName: "Плащ", index: "2265", slot: "cape" },
  {
    name: "T8_CAPEITEM_FW_BRIDGEWATCH",
    ruName: "Накидка города Bridgewatch",
    index: "2290",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_FW_FORTSTERLING",
    ruName: "Накидка города Fort Sterling",
    index: "2315",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_FW_LYMHURST",
    ruName: "Накидка города Lymhurst",
    index: "2340",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_FW_MARTLOCK",
    ruName: "Накидка города Martlock",
    index: "2365",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_FW_THETFORD",
    ruName: "Накидка города Thetford",
    index: "2390",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_FW_CAERLEON",
    ruName: "Плащ города Caerleon",
    index: "2415",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_FW_BRECILIEN",
    ruName: "Плащ города Brecilien",
    index: "2440",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_AVALON",
    ruName: "Авалонский плащ",
    index: "2465",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_HERETIC",
    ruName: "Плащ Еретиков",
    index: "2490",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_UNDEAD",
    ruName: "Плащ Нежити",
    index: "2515",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_KEEPER",
    ruName: "Плащ Хранителей",
    index: "2540",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_MORGANA",
    ruName: "Плащ Морганы",
    index: "2565",
    slot: "cape",
  },
  {
    name: "T8_CAPEITEM_DEMON",
    ruName: "Плащ Демонов",
    index: "2590",
    slot: "cape",
  },
  {
    name: "T8_HEAD_PLATE_SET1",
    ruName: "Шлем солдата",
    index: "3162",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_SET1",
    ruName: "Броня солдата",
    index: "3189",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_SET1",
    ruName: "Сапоги солдата",
    index: "3216",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_SET2",
    ruName: "Шлем рыцаря",
    index: "3241",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_SET2",
    ruName: "Броня рыцаря",
    index: "3266",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_SET2",
    ruName: "Сапоги рыцаря",
    index: "3291",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_SET3",
    ruName: "Шлем хранителя",
    index: "3316",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_SET3",
    ruName: "Броня хранителя",
    index: "3341",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_SET3",
    ruName: "Сапоги хранителя",
    index: "3366",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_SET1",
    ruName: "Капюшон наемника",
    index: "3769",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_SET1",
    ruName: "Куртка наемника",
    index: "3797",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_SET1",
    ruName: "Ботинки наемника",
    index: "3825",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_SET2",
    ruName: "Капюшон охотника",
    index: "3850",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_SET2",
    ruName: "Куртка охотника",
    index: "3875",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_SET2",
    ruName: "Ботинки охотника",
    index: "3900",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_SET3",
    ruName: "Капюшон убийцы",
    index: "3925",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_SET3",
    ruName: "Куртка убийцы",
    index: "3950",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_SET3",
    ruName: "Ботинки убийцы",
    index: "3975",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_SET1",
    ruName: "Колпак ученого",
    index: "4377",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_SET1",
    ruName: "Мантия ученого",
    index: "4404",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_SET1",
    ruName: "Сандалии ученого",
    index: "4431",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_SET2",
    ruName: "Колпак клирика",
    index: "4456",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_SET2",
    ruName: "Мантия клирика",
    index: "4481",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_SET2",
    ruName: "Сандалии клирика",
    index: "4506",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_SET3",
    ruName: "Колпак чародея",
    index: "4531",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_SET3",
    ruName: "Мантия чародея",
    index: "4556",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_SET3",
    ruName: "Сандалии чародея",
    index: "4581",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_UNDEAD",
    ruName: "Могильный шлем",
    index: "3391",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_UNDEAD",
    ruName: "Могильная броня",
    index: "3416",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_UNDEAD",
    ruName: "Могильные сапоги",
    index: "3441",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_HELL",
    ruName: "Демонический шлем",
    index: "3466",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_HELL",
    ruName: "Демоническая броня",
    index: "3491",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_HELL",
    ruName: "Демонические сапоги",
    index: "3516",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_KEEPER",
    ruName: "Шлем вершителя",
    index: "3541",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_KEEPER",
    ruName: "Броня вершителя",
    index: "3566",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_KEEPER",
    ruName: "Сапоги вершителя",
    index: "3591",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_FEY",
    ruName: "Шлем сумеречного ткача",
    index: "3616",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_FEY",
    ruName: "Броня сумеречного ткача",
    index: "3641",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_FEY",
    ruName: "Сапоги сумеречного ткача",
    index: "3666",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_AVALON",
    ruName: "Шлем доблести",
    index: "3691",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_AVALON",
    ruName: "Броня доблести",
    index: "3716",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_AVALON",
    ruName: "Сапоги доблести",
    index: "3741",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_MORGANA",
    ruName: "Капюшон лазутчика",
    index: "4000",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_MORGANA",
    ruName: "Куртка лазутчика",
    index: "4025",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_MORGANA",
    ruName: "Ботинки лазутчика",
    index: "4050",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_HELL",
    ruName: "Адский капюшон",
    index: "4075",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_HELL",
    ruName: "Адская куртка",
    index: "4100",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_HELL",
    ruName: "Адские ботинки",
    index: "4125",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_UNDEAD",
    ruName: "Капюшон призрака",
    index: "4150",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_UNDEAD",
    ruName: "Куртка призрака",
    index: "4175",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_UNDEAD",
    ruName: "Ботинки призрака",
    index: "4200",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_FEY",
    ruName: "Капюшон туманного охотника",
    index: "4225",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_FEY",
    ruName: "Куртка туманного охотника",
    index: "4250",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_FEY",
    ruName: "Ботинки туманного охотника",
    index: "4275",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_AVALON",
    ruName: "Капюшон упорства",
    index: "4300",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_AVALON",
    ruName: "Куртка упорства",
    index: "4325",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_AVALON",
    ruName: "Ботинки упорства",
    index: "4350",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_KEEPER",
    ruName: "Колпак друида",
    index: "4606",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_KEEPER",
    ruName: "Мантия друида",
    index: "4631",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_KEEPER",
    ruName: "Сандалии друида",
    index: "4656",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_HELL",
    ruName: "Дьявольский колпак",
    index: "4681",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_HELL",
    ruName: "Дьявольская мантия",
    index: "4706",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_HELL",
    ruName: "Дьявольские сандалии",
    index: "4731",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_MORGANA",
    ruName: "Колпак культиста",
    index: "4756",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_MORGANA",
    ruName: "Мантия культиста",
    index: "4781",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_MORGANA",
    ruName: "Сандалии культиста",
    index: "4806",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_FEY",
    ruName: "Шляпа из сказочной чешуи",
    index: "4831",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_FEY",
    ruName: "Мантия из сказочной чешуи",
    index: "4856",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_FEY",
    ruName: "Сандалии из сказочной чешуи",
    index: "4881",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_AVALON",
    ruName: "Колпак чистоты",
    index: "4906",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_AVALON",
    ruName: "Мантия чистоты",
    index: "4931",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_AVALON",
    ruName: "Сандалии чистоты",
    index: "4956",
    slot: "boots",
  },
  {
    name: "T8_HEAD_CLOTH_ROYAL",
    ruName: "Королевский колпак",
    index: "4981",
    slot: "head",
  },
  {
    name: "T8_ARMOR_CLOTH_ROYAL",
    ruName: "Королевская мантия",
    index: "5006",
    slot: "chest",
  },
  {
    name: "T8_SHOES_CLOTH_ROYAL",
    ruName: "Королевские сандалии",
    index: "5031",
    slot: "boots",
  },
  {
    name: "T8_HEAD_LEATHER_ROYAL",
    ruName: "Королевский капюшон",
    index: "5056",
    slot: "head",
  },
  {
    name: "T8_ARMOR_LEATHER_ROYAL",
    ruName: "Королевская куртка",
    index: "5081",
    slot: "chest",
  },
  {
    name: "T8_SHOES_LEATHER_ROYAL",
    ruName: "Королевские ботинки",
    index: "5106",
    slot: "boots",
  },
  {
    name: "T8_HEAD_PLATE_ROYAL",
    ruName: "Королевский шлем",
    index: "5131",
    slot: "head",
  },
  {
    name: "T8_ARMOR_PLATE_ROYAL",
    ruName: "Королевская броня",
    index: "5156",
    slot: "chest",
  },
  {
    name: "T8_SHOES_PLATE_ROYAL",
    ruName: "Королевские сапоги",
    index: "5181",
    slot: "boots",
  },
  {
    name: "T8_HEAD_GATHERER_FIBER",
    ruName: "Шапка жнеца",
    index: "5206",
    slot: "head",
  },
  {
    name: "T8_ARMOR_GATHERER_FIBER",
    ruName: "Одежда жнеца",
    index: "5231",
    slot: "chest",
  },
  {
    name: "T8_SHOES_GATHERER_FIBER",
    ruName: "Рабочие сапоги жнеца",
    index: "5256",
    slot: "boots",
  },
  {
    name: "T8_HEAD_GATHERER_HIDE",
    ruName: "Шапка свежевателя",
    index: "5306",
    slot: "head",
  },
  {
    name: "T8_ARMOR_GATHERER_HIDE",
    ruName: "Одежда свежевателя",
    index: "5331",
    slot: "chest",
  },
  {
    name: "T8_SHOES_GATHERER_HIDE",
    ruName: "Рабочие сапоги свежевателя",
    index: "5356",
    slot: "boots",
  },
  {
    name: "T8_HEAD_GATHERER_ORE",
    ruName: "Шапка шахтера",
    index: "5406",
    slot: "head",
  },
  {
    name: "T8_ARMOR_GATHERER_ORE",
    ruName: "Одежда шахтера",
    index: "5431",
    slot: "chest",
  },
  {
    name: "T8_SHOES_GATHERER_ORE",
    ruName: "Рабочие сапоги шахтера",
    index: "5456",
    slot: "boots",
  },
  {
    name: "T8_HEAD_GATHERER_ROCK",
    ruName: "Шапка каменолома",
    index: "5506",
    slot: "head",
  },
  {
    name: "T8_ARMOR_GATHERER_ROCK",
    ruName: "Одежда каменолома",
    index: "5531",
    slot: "chest",
  },
  {
    name: "T8_SHOES_GATHERER_ROCK",
    ruName: "Рабочие сапоги каменолома",
    index: "5556",
    slot: "boots",
  },
  {
    name: "T8_HEAD_GATHERER_WOOD",
    ruName: "Шапка дровосека",
    index: "5606",
    slot: "head",
  },
  {
    name: "T8_ARMOR_GATHERER_WOOD",
    ruName: "Одежда дровосека",
    index: "5631",
    slot: "chest",
  },
  {
    name: "T8_SHOES_GATHERER_WOOD",
    ruName: "Рабочие сапоги дровосека",
    index: "5656",
    slot: "boots",
  },
  {
    name: "T8_HEAD_GATHERER_FISH",
    ruName: "Шапка рыбака",
    index: "5706",
    slot: "head",
  },
  {
    name: "T8_ARMOR_GATHERER_FISH",
    ruName: "Одежда рыбака",
    index: "5731",
    slot: "chest",
  },
  {
    name: "T8_SHOES_GATHERER_FISH",
    ruName: "Рабочие сапоги рыбака",
    index: "5756",
    slot: "boots",
  },
  
  { name: "T8_2H_BOW", ruName: "Лук", index: "6018", slot: "weapon" },
  {
    name: "T8_2H_WARBOW",
    ruName: "Боевой лук",
    index: "6043",
    slot: "weapon",
  },
  {
    name: "T8_2H_LONGBOW",
    ruName: "Длинный лук",
    index: "6068",
    slot: "weapon",
  },
  {
    name: "T8_2H_LONGBOW_UNDEAD",
    ruName: "Шепчущий лук",
    index: "6093",
    slot: "weapon",
  },
  {
    name: "T8_2H_BOW_HELL",
    ruName: "Воющий лук",
    index: "6118",
    slot: "weapon",
  },
  {
    name: "T8_2H_BOW_KEEPER",
    ruName: "Лук Бадона",
    index: "6143",
    slot: "weapon",
  },
  {
    name: "T8_2H_BOW_AVALON",
    ruName: "Туманный пронзатель",
    index: "6168",
    slot: "weapon",
  },
  {
    name: "T8_2H_CROSSBOW",
    ruName: "Арбалет",
    index: "6199",
    slot: "weapon",
  },
  {
    name: "T8_2H_CROSSBOWLARGE",
    ruName: "Тяжелый арбалет",
    index: "6224",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_1HCROSSBOW",
    ruName: "Легкий арбалет",
    index: "6249",
    slot: "weapon",
  },
  {
    name: "T8_2H_REPEATINGCROSSBOW_UNDEAD",
    ruName: "Плачущий арбалет",
    index: "6274",
    slot: "weapon",
  },
  {
    name: "T8_2H_DUALCROSSBOW_HELL",
    ruName: "Самострелы",
    index: "6299",
    slot: "weapon",
  },
  {
    name: "T8_2H_CROSSBOWLARGE_MORGANA",
    ruName: "Осадный арбалет",
    index: "6324",
    slot: "weapon",
  },
  {
    name: "T8_2H_CROSSBOW_CANNON_AVALON",
    ruName: "Творец энергии",
    index: "6349",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_CURSEDSTAFF",
    ruName: "Проклятый посох",
    index: "6375",
    slot: "weapon",
  },
  {
    name: "T8_2H_CURSEDSTAFF",
    ruName: "Большой проклятый посох",
    index: "6400",
    slot: "weapon",
  },
  {
    name: "T8_2H_DEMONICSTAFF",
    ruName: "Демонический посох",
    index: "6425",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_CURSEDSTAFF_UNDEAD",
    ruName: "Гибельный посох",
    index: "6450",
    slot: "weapon",
  },
  {
    name: "T8_2H_SKULLORB_HELL",
    ruName: "Проклятый череп",
    index: "6475",
    slot: "weapon",
  },
  {
    name: "T8_2H_CURSEDSTAFF_MORGANA",
    ruName: "Посох обреченности",
    index: "6500",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_CURSEDSTAFF_AVALON",
    ruName: "Призыватель теней",
    index: "6525",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_FIRESTAFF",
    ruName: "Огненный посох",
    index: "6552",
    slot: "weapon",
  },
  {
    name: "T8_2H_FIRESTAFF",
    ruName: "Большой огненный посох",
    index: "6577",
    slot: "weapon",
  },
  {
    name: "T8_2H_INFERNOSTAFF",
    ruName: "Адский посох",
    index: "6602",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_FIRESTAFF_KEEPER",
    ruName: "Посох лесного пожара",
    index: "6627",
    slot: "weapon",
  },
  {
    name: "T8_2H_FIRESTAFF_HELL",
    ruName: "Посох серы",
    index: "6652",
    slot: "weapon",
  },
  {
    name: "T8_2H_INFERNOSTAFF_MORGANA",
    ruName: "Пылающий посох",
    index: "6677",
    slot: "weapon",
  },
  {
    name: "T8_2H_FIRE_RINGPAIR_AVALON",
    ruName: "Песнь рассвета",
    index: "6702",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_FROSTSTAFF",
    ruName: "Морозный посох",
    index: "6733",
    slot: "weapon",
  },
  {
    name: "T8_2H_FROSTSTAFF",
    ruName: "Большой морозный посох",
    index: "6758",
    slot: "weapon",
  },
  {
    name: "T8_2H_GLACIALSTAFF",
    ruName: "Ледяной посох",
    index: "6783",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_FROSTSTAFF_KEEPER",
    ruName: "Посох инея",
    index: "6808",
    slot: "weapon",
  },
  {
    name: "T8_2H_ICEGAUNTLETS_HELL",
    ruName: "Заледенелый посох",
    index: "6833",
    slot: "weapon",
  },
  {
    name: "T8_2H_ICECRYSTAL_UNDEAD",
    ruName: "Призма вечного холода",
    index: "6858",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_FROSTSTAFF_AVALON",
    ruName: "Леденящий вой",
    index: "6883",
    slot: "weapon",
  },
  {
    name: "T8_2H_FROSTSTAFF_CRYSTAL",
    ruName: "Снежный посох",
    index: "6908",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_ARCANESTAFF",
    ruName: "Мистический посох",
    index: "6934",
    slot: "weapon",
  },
  {
    name: "T8_2H_ARCANESTAFF",
    ruName: "Большой мистический посох",
    index: "6959",
    slot: "weapon",
  },
  {
    name: "T8_2H_ENIGMATICSTAFF",
    ruName: "Загадочный посох",
    index: "6984",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_ARCANESTAFF_UNDEAD",
    ruName: "Ведьмовской посох",
    index: "7009",
    slot: "weapon",
  },
  {
    name: "T8_2H_ARCANESTAFF_HELL",
    ruName: "Оккультный посох",
    index: "7034",
    slot: "weapon",
  },
  {
    name: "T8_2H_ENIGMATICORB_MORGANA",
    ruName: "Средоточие злобы",
    index: "7059",
    slot: "weapon",
  },
  {
    name: "T8_2H_ARCANE_RINGPAIR_AVALON",
    ruName: "Песнь заката",
    index: "7084",
    slot: "weapon",
  },
  {
    name: "T8_2H_ARCANESTAFF_CRYSTAL",
    ruName: "Астральный посох",
    index: "7109",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_HOLYSTAFF",
    ruName: "Священный посох",
    index: "7135",
    slot: "weapon",
  },
  {
    name: "T8_2H_HOLYSTAFF",
    ruName: "Большой священный посох",
    index: "7160",
    slot: "weapon",
  },
  {
    name: "T8_2H_DIVINESTAFF",
    ruName: "Божественный посох",
    index: "7185",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_HOLYSTAFF_MORGANA",
    ruName: "Посох жизни",
    index: "7210",
    slot: "weapon",
  },
  {
    name: "T8_2H_HOLYSTAFF_HELL",
    ruName: "Посох падших",
    index: "7235",
    slot: "weapon",
  },
  {
    name: "T8_2H_HOLYSTAFF_UNDEAD",
    ruName: "Посох искупления",
    index: "7260",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_HOLYSTAFF_AVALON",
    ruName: "Благодатный посох",
    index: "7285",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_NATURESTAFF",
    ruName: "Древесный посох",
    index: "7316",
    slot: "weapon",
  },
  {
    name: "T8_2H_NATURESTAFF",
    ruName: "Большой древесный посох",
    index: "7341",
    slot: "weapon",
  },
  {
    name: "T8_2H_WILDSTAFF",
    ruName: "Дикий посох",
    index: "7366",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_NATURESTAFF_KEEPER",
    ruName: "Друидский посох",
    index: "7391",
    slot: "weapon",
  },
  {
    name: "T8_2H_NATURESTAFF_HELL",
    ruName: "Посох порчи",
    index: "7416",
    slot: "weapon",
  },
  {
    name: "T8_2H_NATURESTAFF_KEEPER",
    ruName: "Неудержимый посох",
    index: "7441",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_NATURESTAFF_AVALON",
    ruName: "Посох железного корня",
    index: "7466",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_DAGGER",
    ruName: "Кинжал",
    index: "7497",
    slot: "weapon",
  },
  {
    name: "T8_2H_DAGGERPAIR",
    ruName: "Парные кинжалы",
    index: "7522",
    slot: "weapon",
  },
  {
    name: "T8_2H_CLAWPAIR",
    ruName: "Когти",
    index: "7547",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_RAPIER_MORGANA",
    ruName: "Кровопускатель",
    index: "7572",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_DAGGER_HELL",
    ruName: "Клык демона",
    index: "7597",
    slot: "weapon",
  },
  {
    name: "T8_2H_DUALSICKLE_UNDEAD",
    ruName: "Вестники смерти",
    index: "7642",
    slot: "weapon",
  },
  {
    name: "T8_2H_DAGGER_KATAR_AVALON",
    ruName: "Укротитель ярости",
    index: "7667",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_SPEAR",
    ruName: "Копье",
    index: "7698",
    slot: "weapon",
  },
  {
    name: "T8_2H_SPEAR",
    ruName: "Пика",
    index: "7723",
    slot: "weapon",
  },
  {
    name: "T8_2H_GLAIVE",
    ruName: "Глефа",
    index: "7748",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_SPEAR_KEEPER",
    ruName: "Копье цапли",
    index: "7773",
    slot: "weapon",
  },
  {
    name: "T8_2H_HARPOON_HELL",
    ruName: "Охотник за душами",
    index: "7798",
    slot: "weapon",
  },
  {
    name: "T8_2H_TRIDENT_UNDEAD",
    ruName: "Трезубец",
    index: "7823",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_SPEAR_LANCE_AVALON",
    ruName: "Копье рассвета",
    index: "7848",
    slot: "weapon",
  },
  {
    name: "T8_2H_GLAIVE_CRYSTAL",
    ruName: "Глефа разлома",
    index: "7873",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_AXE",
    ruName: "Боевой топор",
    index: "7899",
    slot: "weapon",
  },
  {
    name: "T8_2H_AXE",
    ruName: "Большой топор",
    index: "7924",
    slot: "weapon",
  },
  {
    name: "T8_2H_HALBERD",
    ruName: "Алебарда",
    index: "7949",
    slot: "weapon",
  },
  {
    name: "T8_2H_HALBERD_MORGANA",
    ruName: "Падальщик",
    index: "7974",
    slot: "weapon",
  },
  {
    name: "T8_2H_SCYTHE_HELL",
    ruName: "Адская коса",
    index: "7999",
    slot: "weapon",
  },
  {
    name: "T8_2H_DUALAXE_KEEPER",
    ruName: "Медвежьи лапы",
    index: "8024",
    slot: "weapon",
  },
  {
    name: "T8_2H_AXE_AVALON",
    ruName: "Разрушитель миров",
    index: "8049",
    slot: "weapon",
  },
  {
    name: "T8_2H_SCYTHE_CRYSTAL",
    ruName: "Хрустальный жнец",
    index: "8074",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_SWORD",
    ruName: "Палаш",
    index: "8102",
    slot: "weapon",
  },
  {
    name: "T8_2H_CLAYMORE",
    ruName: "Клеймор",
    index: "8127",
    slot: "weapon",
  },
  {
    name: "T8_2H_DUALSWORD",
    ruName: "Парные мечи",
    index: "8152",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_SCIMITAR_MORGANA",
    ruName: "Королевский меч",
    index: "8177",
    slot: "weapon",
  },
  {
    name: "T8_2H_CLEAVER_HELL",
    ruName: "Меч резни",
    index: "8202",
    slot: "weapon",
  },
  {
    name: "T8_2H_DUALSCIMITAR_UNDEAD",
    ruName: "Парные галатины",
    index: "8227",
    slot: "weapon",
  },
  {
    name: "T8_2H_CLAYMORE_AVALON",
    ruName: "Царетворец",
    index: "8252",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_SWORD_CRYSTAL",
    ruName: "Клинок бесконечности",
    index: "8277",
    slot: "weapon",
  },
  {
    name: "T8_2H_QUARTERSTAFF",
    ruName: "Боевой шест",
    index: "8303",
    slot: "weapon",
  },
  {
    name: "T8_2H_IRONCLADEDSTAFF",
    ruName: "Железный посох",
    index: "8328",
    slot: "weapon",
  },
  {
    name: "T8_2H_DOUBLEBLADEDSTAFF",
    ruName: "Острый шест",
    index: "8353",
    slot: "weapon",
  },
  {
    name: "T8_2H_COMBATSTAFF_MORGANA",
    ruName: "Посох черного монаха",
    index: "8378",
    slot: "weapon",
  },
  {
    name: "T8_2H_TWINSCYTHE_HELL",
    ruName: "Коса душ",
    index: "8403",
    slot: "weapon",
  },
  {
    name: "T8_2H_ROCKSTAFF_KEEPER",
    ruName: "Посох равновесия",
    index: "8428",
    slot: "weapon",
  },
  {
    name: "T8_2H_QUARTERSTAFF_AVALON",
    ruName: "Искатель Грааля",
    index: "8453",
    slot: "weapon",
  },
  {
    name: "T8_2H_DOUBLEBLADEDSTAFF_CRYSTAL",
    ruName: "Парный призрачный клинок",
    index: "8478",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_HAMMER",
    ruName: "Молот",
    index: "8504",
    slot: "weapon",
  },
  {
    name: "T8_2H_POLEHAMMER",
    ruName: "Чекан",
    index: "8529",
    slot: "weapon",
  },
  {
    name: "T8_2H_HAMMER",
    ruName: "Большой молот",
    index: "8554",
    slot: "weapon",
  },
  {
    name: "T8_2H_HAMMER_UNDEAD",
    ruName: "Могильный молот",
    index: "8579",
    slot: "weapon",
  },
  {
    name: "T8_2H_DUALHAMMER_HELL",
    ruName: "Молоты кузни",
    index: "8604",
    slot: "weapon",
  },
  {
    name: "T8_2H_RAM_KEEPER",
    ruName: "Хранитель рощи",
    index: "8629",
    slot: "weapon",
  },
  {
    name: "T8_2H_HAMMER_AVALON",
    ruName: "Длань правосудия",
    index: "8654",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_MACE",
    ruName: "Булава",
    index: "8685",
    slot: "weapon",
  },
  {
    name: "T8_2H_MACE",
    ruName: "Тяжелая булава",
    index: "8710",
    slot: "weapon",
  },
  {
    name: "T8_2H_FLAIL",
    ruName: "Моргенштерн",
    index: "8735",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_ROCKMACE_KEEPER",
    ruName: "Каменная булава",
    index: "8760",
    slot: "weapon",
  },
  {
    name: "T8_MAIN_MACE_HELL",
    ruName: "Булава инкуба",
    index: "8785",
    slot: "weapon",
  },
  {
    name: "T8_2H_MACE_MORGANA",
    ruName: "Булава Камланна",
    index: "8810",
    slot: "weapon",
  },
  {
    name: "T8_2H_DUALMACE_AVALON",
    ruName: "Хранители клятвы",
    index: "8835",
    slot: "weapon",
  },
  {
    name: "T8_2H_KNUCKLES_KEEPER",
    ruName: "Медвежьи перчатки",
    index: "8941",
    slot: "weapon",
  },
  {
    name: "T8_2H_KNUCKLES_HELL",
    ruName: "Адские длани",
    index: "8966",
    slot: "weapon",
  },
  {
    name: "T8_2H_KNUCKLES_MORGANA",
    ruName: "Вороний цестус",
    index: "8991",
    slot: "weapon",
  },
  {
    name: "T8_2H_KNUCKLES_AVALON",
    ruName: "Кулаки Авалона",
    index: "9016",
    slot: "weapon",
  },
  {
    name: "T8_2H_SHAPESHIFTER_MORGANA",
    ruName: "Посох Кровавой луны",
    index: "9122",
    slot: "weapon",
  },
  {
    name: "T8_2H_SHAPESHIFTER_HELL",
    ruName: "Посох порождений Ада",
    index: "9147",
    slot: "weapon",
  },
  {
    name: "T8_2H_SHAPESHIFTER_KEEPER",
    ruName: "Рунный посох Земли",
    index: "9172",
    slot: "weapon",
  },
  {
    name: "T8_2H_SHAPESHIFTER_AVALON",
    ruName: "Светоч",
    index: "9197",
    slot: "weapon",
  },
  {
    name: "T1_MEAL_GRILLEDFISH",
    ruName: "Жареная рыба",
    index: "646",
    slot: "food",
  },
  {
    name: "T1_MEAL_SEAWEEDSALAD",
    ruName: "Салат из водорослей",
    index: "647",
    slot: "food",
  },
  {
    name: "T1_MEAL_SOUP",
    ruName: "Морковный суп",
    index: "648",
    slot: "food",
  },
  {
    name: "T3_MEAL_SOUP",
    ruName: "Пшеничная похлебка",
    index: "652",
    slot: "food",
  },
  {
    name: "T5_MEAL_SOUP",
    ruName: "Капустный суп",
    index: "656",
    slot: "food",
  },
  {
    name: "T1_MEAL_SOUP_FISH",
    ruName: "Суп из илистых моллюсков",
    index: "660",
    slot: "food",
  },
  {
    name: "T3_MEAL_SOUP_FISH",
    ruName: "Суп из грязевых моллюсков",
    index: "664",
    slot: "food",
  },
  {
    name: "T5_MEAL_SOUP_FISH",
    ruName: "Суп из черноводных моллюсков",
    index: "668",
    slot: "food",
  },
  {
    name: "T2_MEAL_SALAD",
    ruName: "Салат с бобами",
    index: "672",
    slot: "food",
  },
  {
    name: "T4_MEAL_SALAD",
    ruName: "Салат с репой",
    index: "676",
    slot: "food",
  },
  {
    name: "T6_MEAL_SALAD",
    ruName: "Картофельный салат",
    index: "680",
    slot: "food",
  },
  {
    name: "T2_MEAL_SALAD_FISH",
    ruName: "Салат с мелководным кальмаром",
    index: "684",
    slot: "food",
  },
  {
    name: "T4_MEAL_SALAD_FISH",
    ruName: "Салат со срединным осьминогом",
    index: "688",
    slot: "food",
  },
  {
    name: "T6_MEAL_SALAD_FISH",
    ruName: "Салат с глубинным кракеном",
    index: "692",
    slot: "food",
  },
  {
    name: "T3_MEAL_PIE",
    ruName: "Пирог с курицей",
    index: "696",
    slot: "food",
  },
  {
    name: "T5_MEAL_PIE",
    ruName: "Пирог с гусятиной",
    index: "700",
    slot: "food",
  },
  {
    name: "T7_MEAL_PIE",
    ruName: "Пирог со свининой",
    index: "704",
    slot: "food",
  },
  {
    name: "T3_MEAL_PIE_FISH",
    ruName: "Пирог с синеглазкой",
    index: "708",
    slot: "food",
  },
  {
    name: "T5_MEAL_PIE_FISH",
    ruName: "Пирог с горной слепоглазкой",
    index: "712",
    slot: "food",
  },
  {
    name: "T7_MEAL_PIE_FISH",
    ruName: "Пирог с морозным смертеглазом",
    index: "716",
    slot: "food",
  },
  {
    name: "T3_MEAL_OMELETTE",
    ruName: "Омлет с курицей",
    index: "720",
    slot: "food",
  },
  {
    name: "T5_MEAL_OMELETTE",
    ruName: "Омлет с гусятиной",
    index: "724",
    slot: "food",
  },
  {
    name: "T7_MEAL_OMELETTE",
    ruName: "Омлет с беконом",
    index: "728",
    slot: "food",
  },
  {
    name: "T3_MEAL_OMELETTE_FISH",
    ruName: "Омлет с мелководным крабом",
    index: "732",
    slot: "food",
  },
  {
    name: "T5_MEAL_OMELETTE_FISH",
    ruName: "Омлет с сухопутным крабом",
    index: "736",
    slot: "food",
  },
  {
    name: "T7_MEAL_OMELETTE_FISH",
    ruName: "Омлет с грязекрабом",
    index: "740",
    slot: "food",
  },
  {
    name: "T3_MEAL_OMELETTE_AVALON",
    ruName: "Авалонский омлет с курятиной",
    index: "744",
    slot: "food",
  },
  {
    name: "T5_MEAL_OMELETTE_AVALON",
    ruName: "Авалонский омлет с гусятиной",
    index: "748",
    slot: "food",
  },
  {
    name: "T7_MEAL_OMELETTE_AVALON",
    ruName: "Авалонский омлет с беконом",
    index: "752",
    slot: "food",
  },
  {
    name: "T4_MEAL_STEW",
    ruName: "Жаркое из козлятины",
    index: "756",
    slot: "food",
  },
  {
    name: "T6_MEAL_STEW",
    ruName: "Жаркое из баранины",
    index: "760",
    slot: "food",
  },
  {
    name: "T8_MEAL_STEW",
    ruName: "Жаркое из говядины",
    index: "764",
    slot: "food",
  },
  {
    name: "T4_MEAL_STEW_FISH",
    ruName: "Жаркое из речного угря",
    index: "768",
    slot: "food",
  },
  {
    name: "T6_MEAL_STEW_FISH",
    ruName: "Жаркое из красноводного угря",
    index: "772",
    slot: "food",
  },
  {
    name: "T8_MEAL_STEW_FISH",
    ruName: "Жаркое из болотного угря",
    index: "776",
    slot: "food",
  },
  {
    name: "T4_MEAL_STEW_AVALON",
    ruName: "Авалонское жаркое из козлятины",
    index: "780",
    slot: "food",
  },
  {
    name: "T6_MEAL_STEW_AVALON",
    ruName: "Авалонское жаркое из баранины",
    index: "784",
    slot: "food",
  },
  {
    name: "T8_MEAL_STEW_AVALON",
    ruName: "Авалонское жаркое из говядины",
    index: "788",
    slot: "food",
  },
  {
    name: "T4_MEAL_SANDWICH",
    ruName: "Сэндвич с козлятиной",
    index: "792",
    slot: "food",
  },
  {
    name: "T6_MEAL_SANDWICH",
    ruName: "Сэндвич с бараниной",
    index: "796",
    slot: "food",
  },
  {
    name: "T8_MEAL_SANDWICH",
    ruName: "Сэндвич с говядиной",
    index: "800",
    slot: "food",
  },
  {
    name: "T4_MEAL_SANDWICH_FISH",
    ruName: "Сэндвич с пестроногим подкаменщиком",
    index: "804",
    slot: "food",
  },
  {
    name: "T6_MEAL_SANDWICH_FISH",
    ruName: "Сэндвич с камышовым подкаменщиком",
    index: "808",
    slot: "food",
  },
  {
    name: "T8_MEAL_SANDWICH_FISH",
    ruName: "Сэндвич с громокрылым подкаменщиком",
    index: "812",
    slot: "food",
  },
  {
    name: "T4_MEAL_SANDWICH_AVALON",
    ruName: "Авалонский сэндвич с козлятиной",
    index: "816",
    slot: "food",
  },
  {
    name: "T6_MEAL_SANDWICH_AVALON",
    ruName: "Авалонский сэндвич с бараниной",
    index: "820",
    slot: "food",
  },
  {
    name: "T8_MEAL_SANDWICH_AVALON",
    ruName: "Авалонский сэндвич с говядиной",
    index: "824",
    slot: "food",
  },
  {
    name: "T3_MEAL_ROAST",
    ruName: "Жареный цыпленок",
    index: "828",
    slot: "food",
  },
  {
    name: "T5_MEAL_ROAST",
    ruName: "Жареный гусь",
    index: "832",
    slot: "food",
  },
  {
    name: "T7_MEAL_ROAST",
    ruName: "Жареная свинина",
    index: "836",
    slot: "food",
  },
  {
    name: "T3_MEAL_ROAST_FISH",
    ruName: "Жареный дымчатый окунь",
    index: "840",
    slot: "food",
  },
  {
    name: "T5_MEAL_ROAST_FISH",
    ruName: "Жареный мглистый окунь",
    index: "844",
    slot: "food",
  },
  {
    name: "T7_MEAL_ROAST_FISH",
    ruName: "Жареный туманный окунь",
    index: "848",
    slot: "food",
  },
];

export default test2;
